web:
    build: ./web
    links:
        - redis
        - db
        - mongo
        - solr
        - gearman
    volumes:
        - /mnt/data/apache2/sites-enabled:/etc/apache2/sites-enabled
        - /mnt/www/regiondo:/mnt/www/regiondo
    ports:
        - "80:80"
        - "443:443"
redis:
    image: redis
    ports:
        - "6379:6379"

db:
    image: percona
    ports:
        - "3306:3306"
    volumes:
        - /mnt/data/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=user
        - MYSQL_PASSWORD=userpass
        - MYSQL_DATABASE=regiondo

mongo:
    build: ./mongo
    volumes:
        - /mnt/data/mongodb:/data/db
    ports:
        - "27017:27017"
solr:
    #image: tehes/solr-3.6
    build: ./solr
    volumes:
        - /mnt/data/solr:/data/db
    ports:
        - "8080:8080"

gearman:
    image: kendu/gearman
    ports:
        - "4730:4730"

